### ISSUE TITLE
Typescript icon changed

### ISSUE THREAD

**Issue by alexey-kozlenkov** [hellopao/vscode-seti-icons#12]
After the last update icon for .ts file has changed.

This is how it looks now (several files on a screenshot):
![image](https://cloud.githubusercontent.com/assets/8117458/19429116/8eaee6c2-9456-11e6-84a4-8ab8de0c548e.png)

vs how it has looked before the update and how it is presented on a home page:

![image](https://cloud.githubusercontent.com/assets/8117458/19429161/c45f7c32-9456-11e6-873d-caecf334c270.png)

Is it scheduled changes (cause I didn't find any mentions in a change-log) or a bug?
Personally, I do like previous variant much more than newer one. :)

**Comment by alexey-kozlenkov** [comment]
Any reaction here?

**Comment by hellopao** [comment]
@alexey-kozlenkov  i'll fix it soon

**Comment by alexey-kozlenkov** [comment]
Fix came with the last (0.1.3) update, grate thanks!
