### ISSUE TITLE
可以给一些文件夹添加个性图标么？

### ISSUE THREAD

**Issue by realmx** [hellopao/vscode-seti-icons#2]
这个插件非常棒，已经在使用了，希望能再优化一下文件夹图标的显示，以及一些专用的文件添加相关的图标，可以参照vscode-icons那样。

最近肩周炎犯了，不然我也可以贡献一点PR🙄

**Comment by hellopao** [comment]
@realmx 下周找个时间我加一下。

**Comment by realmx** [comment]
@hellopao 顺便加个CHANGELOG.md，便于查阅修改日志
