### ISSUE TITLE
Missing icon for src folder?

### ISSUE THREAD

**Issue by roblourens** [hellopao/vscode-seti-icons#5]
Noticed this today, seems fine for everything else -

![image](https://cloud.githubusercontent.com/assets/323878/18475865/53ccf2f4-79c8-11e6-919a-b0baade37ff3.png)

**Comment by JohanBeekers** [comment]
I can confirm this problem. No icon for my 'src' folder either.

**Comment by hellopao** [comment]
@roblourens @JohanBeekers  i've fixed it in v0.0.9
